package com.project.socc.enums;

public enum ProfileRole {
    ADMINISTRATOR,
    COURSE_COORDINATOR,
    ASSISTANT_COURSE_COORDINATOR,
    PROFESSOR,
    ACADEMIC_SECRETARY,
    TECHNICAL_PEDAGOGICAL_STAFF,
    STUDENT,
    PEDAGOGICAL_CURATOR,
    DIRECTOR,
    DEPUTY_DIRECTOR,
    BOARD_MEMBER
}
